# Generated by Django 3.1.2 on 2020-11-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_tbl',
            fields=[
                ('c_no', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=10, null=True)),
                ('c_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('c_gender', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성')], max_length=10, null=True)),
                ('c_birth', models.DateField(blank=True, null=True)),
                ('c_code', models.CharField(blank=True, max_length=6, null=True)),
                ('c_add', models.CharField(blank=True, max_length=50, null=True)),
                ('c_school', models.CharField(blank=True, max_length=50, null=True)),
                ('c_state', models.BooleanField(blank=True, null=True)),
                ('c_out', models.DateField(blank=True, null=True)),
                ('c_code_valid', models.CharField(max_length=6, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='faq_tbl',
            fields=[
                ('faq_no', models.AutoField(primary_key=True, serialize=False)),
                ('faq_question', models.TextField()),
                ('faq_answer', models.TextField()),
                ('faq_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='lecture_tbl',
            fields=[
                ('l_no', models.AutoField(primary_key=True, serialize=False)),
                ('l_totalnum', models.IntegerField()),
                ('l_term', models.IntegerField(choices=[(1, '1개월'), (2, '2개월'), (3, '3개월')])),
                ('l_pay', models.IntegerField(choices=[(280000, '중등 : 280,000원'), (350000, '고등 : 350,000원')])),
                ('l_startdate', models.DateField()),
                ('l_desc', models.CharField(max_length=200, null=True)),
                ('l_img', models.ImageField(null=True, upload_to='lecture/%Y/%m/%d')),
                ('l_dept', models.CharField(choices=[('중등', '중등'), ('고등', '고등')], max_length=20)),
                ('l_class', models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notice_tbl',
            fields=[
                ('notice_no', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(max_length=200)),
                ('n_writer', models.CharField(max_length=20)),
                ('notice_date', models.DateTimeField()),
                ('notice_target', models.CharField(choices=[('선생님', '선생님'), ('전체', '전체')], max_length=20)),
                ('notice_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userpage_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_img_main', models.ImageField(blank=True, null=True, upload_to='userpage/')),
                ('page_img_sub1', models.ImageField(blank=True, null=True, upload_to='userpage/')),
                ('page_img_sub2', models.ImageField(blank=True, null=True, upload_to='userpage/')),
            ],
        ),
        migrations.CreateModel(
            name='training_tbl',
            fields=[
                ('tr_no', models.AutoField(primary_key=True, serialize=False)),
                ('tr_date', models.DateField(auto_now_add=True)),
                ('c_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.customer_tbl')),
                ('l_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.lecture_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='test_tbl',
            fields=[
                ('te_no', models.AutoField(primary_key=True, serialize=False)),
                ('te_name', models.CharField(max_length=200)),
                ('te_score', models.IntegerField(blank=True, null=True)),
                ('te_date', models.DateField()),
                ('tr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.training_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_tbl',
            fields=[
                ('t_no', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=10)),
                ('t_phone', models.CharField(max_length=20, null=True)),
                ('t_gender', models.CharField(choices=[('남', '남'), ('여', '여')], max_length=10)),
                ('t_subject', models.CharField(blank=True, choices=[('수학', '수학'), ('영어', '영어')], max_length=10, null=True)),
                ('t_birth', models.DateField()),
                ('t_state', models.BooleanField()),
                ('t_add', models.CharField(max_length=50, null=True)),
                ('t_join', models.DateField(auto_now_add=True)),
                ('t_file', models.ImageField(blank=True, upload_to='teacher/')),
                ('t_out', models.DateField(null=True)),
                ('t_text', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='online_tbl',
            fields=[
                ('on_no', models.AutoField(primary_key=True, serialize=False)),
                ('on_title', models.CharField(max_length=200)),
                ('on_content', models.TextField()),
                ('on_date', models.DateTimeField()),
                ('on_div', models.CharField(max_length=20)),
                ('l_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.lecture_tbl')),
            ],
        ),
        migrations.AddField(
            model_name='lecture_tbl',
            name='t_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.teacher_tbl'),
        ),
        migrations.CreateModel(
            name='consult_tbl',
            fields=[
                ('cu_no', models.AutoField(primary_key=True, serialize=False)),
                ('cu_cust', models.CharField(max_length=20)),
                ('cu_join_time', models.DateTimeField()),
                ('cu_res_time', models.DateTimeField()),
                ('cu_content', models.TextField(blank=True, null=True)),
                ('cu_state', models.CharField(blank=True, max_length=10, null=True)),
                ('c_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.customer_tbl')),
                ('t_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.training_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='attendance_tbl',
            fields=[
                ('at_no', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.CharField(max_length=20)),
                ('at_date', models.DateField()),
                ('tr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.training_tbl')),
            ],
        ),
    ]
