# Generated by Django 3.1.2 on 2020-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20201117_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_file',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/'),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_gender',
            field=models.CharField(blank=True, choices=[('남', '남'), ('여', '여')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_tbl',
            name='t_state',
            field=models.BooleanField(null=True),
        ),
    ]
