# Generated by Django 3.1.2 on 2020-11-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_auto_20201117_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tbl',
            name='c_join',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
