# Generated by Django 3.1.2 on 2020-11-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20201118_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_tbl',
            name='l_pay',
            field=models.IntegerField(),
        ),
    ]
