# Generated by Django 3.1.2 on 2020-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_consult_tbl_cu_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_tbl',
            name='c_auth',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='teacher_tbl',
            name='c_auth',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
