# Generated by Django 3.1.2 on 2020-11-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20201120_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_tbl',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='online_tbl',
            name='on_file',
            field=models.FileField(blank=True, null=True, upload_to='online/'),
        ),
    ]
