# Generated by Django 3.1.2 on 2020-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0010_auto_20201123_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult_tbl',
            name='cu_join_time',
            field=models.DateTimeField(null=True),
        ),
    ]
