# Generated by Django 3.1.2 on 2020-11-25 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0011_auto_20201124_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_tbl',
        ),
    ]
