# Generated by Django 3.1.2 on 2020-11-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0012_delete_test_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_tbl',
            fields=[
                ('te_no', models.AutoField(primary_key=True, serialize=False)),
                ('te_name', models.CharField(blank=True, max_length=200, null=True)),
                ('te_join', models.DateField(auto_now_add=True)),
                ('l_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.lecture_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='test_detail_tbl',
            fields=[
                ('td_no', models.AutoField(primary_key=True, serialize=False)),
                ('td_question_no', models.IntegerField()),
                ('td_question', models.CharField(blank=True, max_length=200, null=True)),
                ('td_choice_1', models.CharField(blank=True, max_length=200, null=True)),
                ('td_choice_2', models.CharField(blank=True, max_length=200, null=True)),
                ('td_choice_3', models.CharField(blank=True, max_length=200, null=True)),
                ('td_choice_4', models.CharField(blank=True, max_length=200, null=True)),
                ('td_answer', models.IntegerField()),
                ('te_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.test_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='test_apply',
            fields=[
                ('ta_no', models.AutoField(primary_key=True, serialize=False)),
                ('ta_date', models.DateField(auto_now_add=True)),
                ('te_score', models.IntegerField()),
                ('te_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.test_tbl')),
                ('tr_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.training_tbl')),
            ],
        ),
    ]
