# Generated by Django 3.1.2 on 2020-11-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0013_test_apply_test_detail_tbl_test_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_detail_tbl',
            name='td_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_detail_tbl',
            name='td_question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
