# Generated by Django 3.1.3 on 2020-12-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_auto_20201201_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult_tbl',
            name='cu_cust',
        ),
    ]
