# Generated by Django 3.1.3 on 2020-12-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0016_auto_20201201_1541'),
        ('admin', '0018_remove_consult_tbl_cu_cust'),
    ]

    operations = [
    ]
