# Generated by Django 3.1.2 on 2020-11-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='success',
            field=models.BooleanField(null=True),
        ),
    ]
