# Generated by Django 3.1.2 on 2020-11-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_tbl',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='customer_tbl',
            name='c_join',
        ),
        migrations.RemoveField(
            model_name='customer_tbl',
            name='c_pw',
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_gender',
            field=models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer_tbl',
            name='c_state',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
